---
# Homepage configuration
# See https://boxicons.com/ for icons options

title: "Homer Minimal"
subtitle: "tchgrbr"
logo: "assets/icons/logo.png"
# icon: "bx bx-bug" # Optional icon

stylesheet:
  - "assets/custom.css"
  - "https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"

header: true
footer: '<p>Crafted with <span class="has-text-danger">❤️</span> by <a href="https://teichgraeber.work">teichgräber</a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#262626"
    highlight-secondary: "#000000"
    highlight-hover: "#5e5e5e"
    background: "#efefef"
    card-background: "#e5e5e5"
    border-color: "#d6d6d6"
    text: "#000000"
    text-header: "#000000"
    text-title: "#000000"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0)
    tag: "#ff5e19"
    link: "#000000"
    link-hover: "#216DFF"
    message-headline: "#111111"
    message-highlight: "#F59D19"
    message-bg: "#F59D1930" # The last two digits define the opacity in %
  dark:
    highlight-primary: "#262626"
    highlight-secondary: "#000000"
    highlight-hover: "#666666"
    background: "#111111"
    card-background: "#262626"
    border-color: "#424242"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#adadad"
    card-shadow: rgba(0, 0, 0, 0)
    tag: "#ffffff"
    link: "#ffffff"
    link-hover: "#216DFF"
    message-headline: "#111111"
    message-highlight: "#F59D19"
    message-bg: "#F59D1925" # The last two digits define the opacity in %

# Optional message
message:
  url: https://teichgraeber.work
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Important: How to modify your Dashboard"
  icon: "bx bxs-bug"
  content: "This is a dummy dashboard demo with placeholder content.<br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"
# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Github"
    icon: "bx bxl-github"
    url: "https://github.com/tchgrbr/homer-minimal"
    target: "_blank" # optional html a tag target attribute
  - name: "Website"
    icon: "bx bx-globe"
    url: "https://teichgraeber.work/"
    target: "_blank"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "bx bx-globe"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "bx bx-atom"
    items:
      - name: "Paperless-ngx"
        logo: "assets/tools/sample.png"
        subtitle: "Document Management"
        tag: "app"
        url: "https://github.com"
        target: "_blank"
      - name: "Plex"
        logo: "assets/tools/sample.png"
        subtitle: "Media Server"
        tag: "app"
        url: "https://github.com"
        target: "_blank"
      - name: "Photoprism"
        logo: "assets/tools/sample.png"
        subtitle: "Photo Backup"
        tag: "app"
        url: "https://github.com"
        target: "_blank"
  - name: "Administration"
    icon: "bx bx-sitemap"
    items:
      - name: "Uptime Kuma"
        logo: "assets/tools/sample2.png"
        subtitle: "Status Dashboard"
        tag: "app"
        url: "https://github.com"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/tools/sample2.png"
        subtitle: "Container Management"
        tag: "app"
        url: "https://github.com"
        target: "_blank"
      - name: "Nginx Proxy Manager"
        logo: "assets/tools/sample2.png"
        subtitle: "Proxy Manager"
        tag: "app"
        url: "https://github.com"
        target: "_blank"